server:
  port: 3001
spring:
  application:
    name: eureka



#eureka配置
eureka:
  client:
#  是否开启
    enabled: true
#    是否注册到注册中心
    register-with-eureka: true
#    检索服务
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:3001/eureka/
#实例信息
  instance:
    ip-address: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000