server:
  port: 3003
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:3002/
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
         # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lower-case-service-id: true
          # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
      - id: client-test
      # uri: http://localhost:9001   #目标服务地址
      #以负载均衡方式路由到目标服务，格式为 lb://服务名
        uri: lb://CLIENT-TEST
        #基于路径的路由策略
        predicates:
          - Path=/testclient/**
        #去掉路径前缀
        filters:
          - StripPrefix=1

      - id: service-feign
        uri: lb://FEIGN
        predicates:
          - Path=/service-feign/**
        filters:
          - StripPrefix=1


#eureka配置
eureka:
  client:
#  是否开启
    enabled: true
#    是否注册到注册中心
    register-with-eureka: true
#    检索服务
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:3001/eureka/
#实例信息
  instance:
    ip-address: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always